using System;
using System.Reflection;
using HarmonyLib;
using Unity.Netcode;
using UnityEngine;

// Harmony patch to reduce linear acceleration from StickPositioner.ApplySoftCollision
// while preserving the torque generated by AddForceAtPosition. This uses the
// "cancel at COM" method: after the original AddForceAtPosition runs we apply
// an opposite force at the Rigidbody COM equal to a fraction of the contact
// force, leaving the torque unchanged.

[HarmonyPatch(typeof(StickPositioner), "ApplySoftCollision")]
static class BoardBounceAdjustments_Patch
{
    // Local configurable defaults — do not rely on ValueTweaks for these.
    // Fraction of the soft-collision linear force to cancel at the Rigidbody COM (0..1).
    // 0 = do not cancel (original behavior). 1 = cancel all linear component (pure rotation).
    public static float SoftCollisionLinearReduction = 0.15f;
    // Fallback soft collision force used if reflection cannot read the instance field.
    public static float SoftCollisionForceDefault = 1f;
    // Enable debug logging for adjustments (may be chatty)
    public static bool DebugLogging = true;
    static void Postfix(StickPositioner __instance, RaycastHit hit, Vector3 hitPosition)
    {
        try
        {
            if (__instance == null) return;
            // Only run on server (physics authority)
            if (NetworkManager.Singleton == null || !NetworkManager.Singleton.IsServer) return;

            // Get PlayerBody Rigidbody
            var playerBody = __instance.PlayerBody;
            if (playerBody == null) return;
            var rb = playerBody.Rigidbody;
            if (rb == null) return;

            // Read configurable reduction fraction from this patch's local config
            float reduction = Mathf.Clamp(SoftCollisionLinearReduction, 0f, 1f);
            if (reduction <= 0f) return; // nothing to do

            // Recompute the contact force used in ApplySoftCollision to match the original
            // F = hit.normal * d * (softCollisionForce * num)
            float maximumReach = 0f;
            GameObject raycastOrigin = null;
            float softCollisionForce = SoftCollisionForceDefault;
            try
            {
                var t = __instance.GetType();

                var fi = t.GetField("maximumReach", BindingFlags.Instance | BindingFlags.NonPublic);
                if (fi != null) maximumReach = (float)fi.GetValue(__instance);
                else
                {
                    var pi = t.GetProperty("maximumReach", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
                    if (pi != null) maximumReach = (float)pi.GetValue(__instance);
                }

                var fi2 = t.GetField("raycastOrigin", BindingFlags.Instance | BindingFlags.NonPublic);
                if (fi2 != null) raycastOrigin = (GameObject)fi2.GetValue(__instance);
                else
                {
                    var pi2 = t.GetProperty("raycastOrigin", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
                    if (pi2 != null) raycastOrigin = (GameObject)pi2.GetValue(__instance);
                }

                var fi3 = t.GetField("softCollisionForce", BindingFlags.Instance | BindingFlags.NonPublic);
                if (fi3 != null) softCollisionForce = (float)fi3.GetValue(__instance);
                else
                {
                    var pi3 = t.GetProperty("softCollisionForce", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
                    if (pi3 != null) softCollisionForce = (float)pi3.GetValue(__instance);
                }
            }
            catch { }

            // If maximumReach wasn't found via reflection, fall back to an estimate using hit.distance
            float d = maximumReach - hit.distance;
            // If raycastOrigin is present, use it to compute the original magnitude factor; otherwise estimate
            float magnitude = 0f;
            try
            {
                if (raycastOrigin != null)
                {
                    magnitude = Vector3.Cross(hit.normal, raycastOrigin.transform.forward).magnitude;
                }
                else
                {
                    // fallback: approximate using hit.normal and player's forward
                    var pl = __instance.transform;
                    magnitude = Vector3.Cross(hit.normal, pl.forward).magnitude;
                }
            }
            catch { magnitude = 0f; }

            

            float num = 1f - magnitude;
            float effectiveSoft = softCollisionForce;

            // Build the exact force vector used by ApplySoftCollision
            Vector3 F = hit.normal * d * (effectiveSoft * num);

            // Compute cancelling force to apply at COM
            Vector3 cancel = -reduction * F;

            // Apply cancellation at COM using same ForceMode (Acceleration) used by ApplySoftCollision
            try
            {
                rb.AddForce(cancel, ForceMode.Acceleration);

                try { if (DebugLogging) Debug.Log($"[BoardBounceAdjustments] Cancelled {reduction * 100f}% of soft collision linear force: cancel={cancel}"); } catch { }
            }
            catch (Exception e)
            {
                try { Debug.LogException(e); } catch { }
            }
        }
        catch (Exception e)
        {
            try { Debug.LogException(e); } catch { }
        }
    }
}
